### ISSUE TITLE
你好，请问你训练的featup可以提供一些吗？谢谢！

### ISSUE THREAD

**Issue by Baobaon** [likyoo/SegEarth-OV#11]

**Comment by likyoo** [comment]
[这里](https://github.com/likyoo/SegEarth-OV/tree/main/simfeatup_dev/weights)有可以直接使用的权重

**Comment by Baobaon** [comment]
> [这里](https://github.com/likyoo/SegEarth-OV/tree/main/simfeatup_dev/weights)有可以直接使用的权重

感谢你的回复！
但是，我出现了如下错误：
![image](https://github.com/user-attachments/assets/2aa13e29-c653-483a-8ef6-8a3763ab0c6d)

**Comment by likyoo** [comment]
这是因为没有成功安装featup哈，参考[这里](https://github.com/likyoo/SimFeatUp)进行安装

**Comment by Baobaon** [comment]
> 这是因为没有成功安装featup哈，参考[这里](https://github.com/likyoo/SimFeatUp)进行安装

感谢你的耐心回复，我已经可以使用了！

**Comment by likyoo** [comment]
不客气~
