### ISSUE TITLE
SAM for RSIs OVSS

### ISSUE THREAD

**Issue by Bili-Sakura** [likyoo/SegEarth-OV#2]
Awesome work!
I wonder whether SAM works well in zero-shot way for remote sensing images segmentation compared to your model.

**Comment by likyoo** [comment]
Thanks for your attention. 
SAM-based OVSS methods are often two-stage: propose class-agnostic masks and classify the masks. They work well in natural images, but we haven't tried them on RS images. We expect that subsequent work will make relevant explorations.

Some related work such as References [2, 23, 56, 60].
