### ISSUE TITLE
questions about other models in demo

### ISSUE THREAD

**Issue by Pengyu-gis** [likyoo/SegEarth-OV#3]
Thank you for sharing this excellent work!

I tried the Colab demo, but I found that I’m unable to use RemoteCLIP or GeoRSCLIP yet. I’m not sure if I’m missing something or if these features are still in progress.

Again, thank you for sharing the code!

```python
model = SegEarthSegmentation(
    clip_type='CLIP',     # 'CLIP', 'BLIP', 'OpenCLIP', 'MetaCLIP', 'ALIP', 'SkyCLIP', 'GeoRSCLIP', 'RemoteCLIP'
    vit_type='ViT-B/16',      # 'ViT-B/16', 'ViT-L-14'
    model_type='SegEarth',   # 'vanilla', 'MaskCLIP', 'GEM', 'SCLIP', 'ClearCLIP', 'SegEarth'
    ignore_residual=True,
    feature_up=True,
    feature_up_cfg=dict(
        model_name='jbu_one',
        model_path='simfeatup_dev/weights/xclip_jbu_one_million_aid.ckpt'),
    cls_token_lambda=-0.3,
    name_path='./configs/my_name.txt',
    prob_thd=0.1,
)
```

**Comment by likyoo** [comment]
Thanks for your attention~
You should first download the checkpoints of RemoteCLIP or GeoRSCLIP:
```wget -P ./checkpoint https://huggingface.co/Zilun/GeoRSCLIP/resolve/main/ckpt/RS5M_ViT-B-32.pt```

But we don't provide simfeatup weights for either model (upsampling 32x), you can [train them](https://github.com/likyoo/SimFeatUp) yourself or try the non-upsampling version:
```
model = SegEarthSegmentation(
    clip_type='GeoRSCLIP',
    vit_type='ViT-B', 
    model_type='SegEarth', 
    ignore_residual=True,
    feature_up=False,
    cls_token_lambda=0,
    name_path='./configs/my_name.txt',
    prob_thd=0.1,
)
```

**Comment by Pengyu-gis** [comment]
Got it! Thank you for the quick reply :)
