### ISSUE TITLE
How to reproduce the same precision as in the paper?

### ISSUE THREAD

**Issue by KotlinWang** [likyoo/SegEarth-OV#5]
I replicated the Potsdam data set according to the steps, and the results were much different from those in the paper. Did I make a mistake in any of my steps?
![20241017110036](https://github.com/user-attachments/assets/a116b9b5-24f6-483b-9866-b10f9b391ca3)

**Comment by likyoo** [comment]
Please make sure that you have [prepared the data](https://github.com/likyoo/SegEarth-OV/blob/main/dataset_prepare.md#isprs-potsdam) correctly.

**Comment by KotlinWang** [comment]
Yes, I built the dataset as required.
![20241017111645](https://github.com/user-attachments/assets/74fca425-d2ad-42d8-9cef-1f97b6466f77)

**Comment by likyoo** [comment]
Could you show some of your cropped images and labels? Did you use a validation set for evaluation?

**Comment by KotlinWang** [comment]
This is the result of running eval.py directly as prompted in README.
![2_10_0_0_512_512_img](https://github.com/user-attachments/assets/74f3fa2a-50de-4970-8886-ef6782092f00)
![2_10_0_0_512_512_lable](https://github.com/user-attachments/assets/2b2ad7df-a276-4686-a1a1-b684ef5c9efe)

**Comment by KotlinWang** [comment]
Each cropped image appears to be a grayscale image.

**Comment by likyoo** [comment]
![image](https://github.com/user-attachments/assets/0b55e405-802e-45ed-ba21-1add16bda0cd)
I retested the script and successfully got the cropped RGB image. Make sure your raw data is correct.

**Comment by likyoo** [comment]
![image](https://github.com/user-attachments/assets/a6156778-5750-49e7-b721-dd93bb1df379)

**Comment by KotlinWang** [comment]
Thank you very much! We used all zip files to build the dataset. Just use '2_Ortho_RGB.zip' and '5_Labels_all_noBoundary.zip' to get an RGB image.
