### ISSUE TITLE
about Colab demo

### ISSUE THREAD

**Issue by XinzheGeng** [likyoo/SegEarth-OV#6]
作者你好，我尝试使用提供的Colab demo时遇到了如下的报错，似乎是timm包的导入问题，请问这个如何解决呢
![image](https://github.com/user-attachments/assets/3281cdd9-de64-4804-9d1d-2034459e921e)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-15-d838e9f3ab58>](https://localhost:8080/#) in <cell line: 7>()
      5 import matplotlib.pyplot as plt
      6 from torchvision import transforms
----> 7 from segearth_segmentor import SegEarthSegmentation
      8 
      9 img = Image.open('demo/oem_koeln_50.tif')

4 frames
[/content/SegEarth-OV/segearth_segmentor.py](https://localhost:8080/#) in <module>
     15 
     16 from open_clip import tokenizer, create_model
---> 17 from BLIP.models.blip_retrieval import blip_retrieval
     18 import gem
     19 from simfeatup_dev.upsamplers import get_upsampler

[/content/SegEarth-OV/BLIP/models/blip_retrieval.py](https://localhost:8080/#) in <module>
      6 import torch.nn.functional as F
      7 
----> 8 from BLIP.models.blip import create_vit, init_tokenizer, load_checkpoint
      9 
     10 class BLIP_Retrieval(nn.Module):

[/content/SegEarth-OV/BLIP/models/blip.py](https://localhost:8080/#) in <module>
      9 warnings.filterwarnings("ignore")
     10 
---> 11 from BLIP.models.vit import VisionTransformer, interpolate_pos_embed
     12 from BLIP.models.med import BertConfig, BertModel, BertLMHeadModel
     13 from transformers import BertTokenizer

[/content/SegEarth-OV/BLIP/models/vit.py](https://localhost:8080/#) in <module>
     15 
     16 from timm.models.vision_transformer import _cfg, PatchEmbed
---> 17 from timm.models.registry import register_model
     18 from timm.models.layers import trunc_normal_, DropPath
     19 from timm.models.helpers import named_apply, adapt_input_conv

[/usr/local/lib/python3.10/dist-packages/timm/models/registry.py](https://localhost:8080/#) in <module>
----> 1 from ._registry import *
      2 
      3 import warnings
      4 warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", DeprecationWarning)

AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'

**Comment by likyoo** [comment]
This was an [error](https://github.com/huggingface/pytorch-image-models/discussions/2306) caused by TIMM and I've fixed it now.
Thanks for pointing this out.
